name: project_belanjakan
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^5.2.0
  awesome_notifications: ^0.7.4+1
  barcode_widget: ^2.0.4
  camera: ^0.10.5+5
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.4.6
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.2
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_nav_bar: ^5.0.6
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.17.0
  lottie: ^2.7.0
  mobile_scanner: ^3.5.2
  mockito: ^5.4.3
  path_provider: ^2.1.1
  pdf: ^3.10.6
  photo_view: ^0.14.0
  printing: ^5.11.1
  responsive_sizer: ^3.2.0
  sensors_plus: ^3.1.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.0
  uuid: ^4.2.1
  vibration: ^1.8.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/animation/
